name = "leanwuzla"
version = "0.1.0"
defaultTargets = ["Leanwuzla", "leanwuzla"]
testRunner = "Test"

[[lean_lib]]
name = "Test"

[[lean_lib]]
name = "Leanwuzla"

[[lean_exe]]
name = "leanwuzla"
root = "Main"
supportInterpreter = true

[[require]]
scope = "leanprover"
name = "Cli"
rev = "55c37290ff6186e2e965d68cf853a57c0702db82"

[[require]]
git = "https://github.com/opencompl/fp-lean"
name = "fp-lean"
rev = "main"
